name: sustainable_living_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.2
  flutter_lints: ^6.0.0
  test: ^1.25.15
  video_player: ^2.8.2
  chewie: ^1.7.1
  provider: ^6.0.5
  image_picker: ^0.8.7+4
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  crypto: ^3.0.3
  sqflite: ^2.2.7
  path: ^1.9.1
  

dev_dependencies:
  flutter_native_splash: ^2.4.0

  flutter_test:
    sdk: flutter
    

flutter:
  uses-material-design: true
  assets:
    - assets/images/travel_banner.jpg
    - assets/images/vengan_stir_fry.jpg
    - assets/images/eco_destination.jpg
    - assets/images/energy_tips_banner.jpg
    - assets/images/education_banner.jpg
    - assets/images/toothbrush.jpg
    - assets/images/totebag.jpg
    - assets/images/solarbank.jpg
    - assets/images/resusable_water_bottle.jpg
    
    # eco-travel-tips
    - assets/images/public_transport.jpg
    - assets/images/carpooling.jpg
    - assets/images/cycling.jpg
    - assets/images/camping.jpg
    - assets/images/national_park.jpg
    - assets/images/e_scooter.jpg
    - assets/images/walking.jpg
    - assets/images/eco_hotel.jpg
    - assets/images/guesthouse.jpg
    - assets/images/eco_resort.jpg
    - assets/images/green_hostel.jpg
    - assets/images/local_destination.jpg
    - assets/images/heritage_site.jpg
    - assets/images/wildlife_sanctuary.jpg
    - assets/images/eco_village.jpg

    # articles
    - assets/images/public_transport.jpg
    - assets/images/plasticfree.jpg
    - assets/images/climate_change.jpg
    - assets/images/renewable_energy.jpg
    - assets/images/water_conservation.jpg

    # profile camera images
    - assets/images/avatar.png
    - assets/images/avatar1.jpg
    - assets/images/avatar2.jpg
    - assets/images/avatar3.jpg
    - assets/images/avatar4.jpg
   
    # recipes
    - assets/images/vengan_stir_fry.jpg
    - assets/images/local_lentil_soup.jpg
    - assets/images/zero_waste_salad.jpg
    - assets/images/quinoa_veggie_bowl.jpg
    - assets/images/chickpea_curry.jpg
    - assets/images/homemade_granola.jpg

    # splash screen logo
    - assets/images/logo.png

# ✅ Splash screen config
flutter_native_splash:
  color: "#ffffff" # background color (white, ap dark bhi kar sakte ho)
  image: assets/images/logo.png # apka logo
  android: true
  ios: true
  web: false
  timeing_native: 1 # native splash screen ka timing (seconds mein)
  timeing_web: 1 # web splash screen ka timing (seconds mein)
  
  